spring.application.name=SpringRabbitMQ

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Optional: make RabbitTemplate use JSON conversion
spring.rabbitmq.template.message-converter=jackson2
